name: Build Android CD/CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
       name: Build APK
       runs-on: ubuntu-latest
       
       steps:
          - name: Checkout source
            uses: actions/checkout@v2

          - name: Setup java
            uses: actions/setup-java@v1
            with:
              java-version: 1.8

          - name: Setup Node.js
            uses: actions/setup-node@v1
            with:
              node-version: 16.x
          
          - name: Install Ionic
            run: npm install -g @ionic/cli

          - name: Install app dependencies
            run: npm install

          - name: Build Ionic App
            run: ionic build

          - name: Copy Android
            run: ionic capacitor copy android

          - name: Build Android Dev APK
            run: ionic capacitor build android -c test

          - name: Make gradlew executable
            working-directory: ./android/
            run: chmod +x ./gradlew

          - name: Generate the Android App Bundle
            working-directory: ./android/
            run: ./gradlew assembleDebug
            
          - name: Upload dev APK
            uses: actions/upload-artifact@v1
            with:
              name: app-dev
              path: ./android/app/build/outputs/apk/debug/app-debug.apk
          - name: Send mail
            uses: dawidd6/action-send-mail@v3
            with:
              # Required mail server address:
              server_address: smtp.163.com
              # Required mail server port:
              server_port: 465
              # Optional (recommended): mail server username:
              username: ljfznet@163.com
              # Optional (recommended) mail server password:
              password: AOZSGPFHUTOWLULR
              # Required mail subject:
              subject: Github Actions job result
               # Required recipients' addresses:
              to: zhengxi.li13@gmail.com
              from: Zhengxi LI # <user@example.com>
              body: Build job of ${{github.repository}} completed successfully!
              attachments: ./android/app/build/outputs/apk/debug/app-debug.apk