name: (STAGING)Build Android CD/CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
       name: Build APK
       runs-on: ubuntu-latest
       environment: TEST
       steps:
          - name: Checkout source
            uses: actions/checkout@v2

          - name: Setup java
            uses: actions/setup-java@v1
            with:
              java-version: 1.8

          - name: Setup Node.js
            uses: actions/setup-node@v1
            with:
              node-version: 16.x
          
          - name: Install Ionic
            run: npm install -g @ionic/cli

          - name: Install app dependencies
            run: npm install

          - name: Build Android APK
            run: ionic capacitor build android -c test

          - name: Update Android version number 
            uses: damienaicheh/update-android-version-manifest-action@v1.0.0
            with:
              android-manifest-path: './android/app/src/main/AndroidManifest.xml'
              version-code: ${{ github.run_number }}
              version-name: ${{ github.run_number }}
              print-file: true

          
          - name: Bump version
            uses: chkfung/android-version-actions@v1.1
            with:
              gradlePath: ./android/app/build.gradle 
              versionCode: ${{github.run_number}}
              versionName: 1.0.0

          - name: Update AndroidManifest.xml
            uses: damienaicheh/update-android-manifest-package-action@v1.0.0
            with:
              android-manifest-path: './android/app/src/main/AndroidManifest.xml'
              package-name: 'io.ionic.ljapp.test'
              app-name: '麗錦紡織(测试)'
              print-file: true

          - name: Make gradlew executable
            working-directory: ./android/
            run: chmod +x ./gradlew

          - name: Generate the Android App Bundle
            working-directory: ./android/
            run: ./gradlew assembleDebug 
              
          - name: Upload dev APK
            uses: actions/upload-artifact@v1
            with:
              name: app-dev
              path: ./android/app/build/outputs/apk/staging/debug/app-staging-debug.apk

          - name: Send mail
            uses: dawidd6/action-send-mail@v3
            with:
              # Required mail server address:
              server_address: smtp.163.com
              # Required mail server port:
              server_port: 465
              # Optional (recommended): mail server username:
              username: ${{secrets.MAIL_USERNAME}}
              # Optional (recommended) mail server password:
              password: ${{secrets.MAIL_PASSWORD}}
              # Required mail subject:
              subject: 手机app测试版发布
               # Required recipients' addresses:
              to: ${{secrets.MAIL_TO}}
              from: 麗錦紡織 # <user@example.com>
              body: 新的测试版已发布，请测试
              attachments: ./android/app/build/outputs/apk/staging/debug/app-staging-debug.apk
